pcm.bluealsa {
    @args [ DEV PROFILE SRV ]
    @args.DEV {
        type string
        default "00:00:00:00:00:00"
    }
    @args.PROFILE {
        type string
        default "a2dp"
    }
    @args.SRV {
        type string
        default "org.bluealsa"
    }
    type plug
    slave.pcm {
        type bluealsa
        device $DEV
        profile $PROFILE
        service $SRV
    }
}

ctl.bluealsa {
    @args [ SRV ]
    @args.SRV {
        type string
        default "org.bluealsa"
    }
    type bluealsa
    service $SRV
}
